apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:    
      containers:
      - name: vote
        image: dockersamples/examplevotingapp_vote:before
        ports:
        - containerPort: 80
          name: vote  
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
  namespace: vote
spec:
  selector:
    app: vote
  type: NodePort
  ports:
  - name: "vote-service"
    port: 5000 #ini port service
    targetPort: 80 #ini port container dari docker image, pastikan di dockerfile port yg diexpose sama dengan ini
    nodePort: 31000 #ini port yg digunakan untuk akses dari luar dengan ip node (lihat di ipconfig to get WSL IP)   